language: python
python:
  - "2.7"
before_install:
  - which "python"
  - python -c "import sys; print sys.path"
addons:
  apt:
    packages:
      - scons
      - docbook-xml
      - xsltproc
      - imagemagick
      - python-epydoc
install:
  - python bin/downloads.py
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - scons --version
script:
  - scons user-doc
  - scons api-doc || true # until python-epydoc is not in whitelist
  - scons unit-test
  - SCONS_EXTERNAL_TEST=1 python runtest.py -a
